import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Wayland
import qs.Commons
import qs.Ui
import "WidgetConfig.js" as Config
import "WidgetTheme.js" as Theme

// Desktop Widgets — floating overlay cards on the desktop.
//
// Architecture:
//   - One full-screen PanelWindow (WlrLayer.Bottom, no exclusion)
//   - Every card is freely positioned via its own x/y in config
//   - Cards are draggable only when edit mode is ON
//   - Edit mode toggles a visual highlight border + enables dragging
//   - Input mask expands to full screen during drag so DragHandler stays active
//   - Right-click a card for context menu (via TapHandler, no overlay MouseArea)
//   - Config persisted to ~/.config/omarchy/tammy-widgets.json
//   - File watcher is suppressed during saves to avoid feedback loops

PanelWindow {
  id: root

  property var shell: null
  property var manifest: null

  property var config: Config.defaultConfig()

  // Emitted whenever config changes in-place. Widgets connect to this
  // to re-read their specific config values — avoids the expensive
  // Qt.binding cascade where ALL widgets re-evaluate on ANY change.
  // Named widgetConfigRefresh to avoid clashing with the built-in
  // configChanged signal generated by the `config` property.
  signal widgetConfigRefresh()

  readonly property string configPath: Config.CONFIG_PATH

  // Suppress file watcher during saves to prevent the feedback loop:
  // save → file changes → reload → parse → set config → triggers bindings
  property bool suppressFileWatch: false

  // Context menu state
  property string contextMenuWidgetId: ""
  property real contextMenuX: 0
  property real contextMenuY: 0
  property bool contextMenuVisible: false

  // Settings panel state
  property bool settingsVisible: false

  // Edit mode: when true, cards show a highlight border.
  // Dragging works regardless of edit mode.
  property bool editMode: false

  // True while any card is being dragged. Suppresses relayout so
  // other auto-positioned cards don't jitter during drag.
  property bool dragInProgress: false

  // Counter that increments every time a card loads/unloads. The mask
  // binding reads this so it re-evaluates and picks up the loaded card
  // items. Without this, cardItemFor() returns null at startup (before
  // Repeaters have loaded anything) and the mask stays empty forever.
  property int cardLoadCounter: 0

  readonly property real barOffset: Style.bar.sizeHorizontal + Style.gapsOut
  readonly property real edgeMargin: 24
  // Reserve space at the bottom for the dock (autohide dock still needs margin)
  readonly property real dockOffset: 60
  readonly property real cardSpacing: {
    var v = root.config && root.config.global ? Number(root.config.global.cardSpacing) : NaN
    return isFinite(v) ? Math.max(0, v) : 12
  }
  readonly property real cardWidth: 300

  function cardItemFor(widgetId) {
    for (var i = 0; i < autoRepeater.count; i++) {
      var l = autoRepeater.itemAt(i)
      if (l && l.item && l.item.widgetId === widgetId) return l.item
    }
    for (var j = 0; j < manualRepeater.count; j++) {
      var ml = manualRepeater.itemAt(j)
      if (ml && ml.item && ml.item.widgetId === widgetId) return ml.item
    }
    return null
  }

  function interactiveCardItemFor(widgetId) {
    var card = root.cardItemFor(widgetId)
    if (!card || (!root.editMode && Config.widgetClickThrough(root.config, widgetId))) return null
    return card
  }

  function widgetSourceUrl(widgetId) {
    var map = {
      systemMonitor: "SystemMonitor.qml",
      battery: "BatteryWidget.qml",
      media: "MediaWidget.qml",
      topProcesses: "TopProcesses.qml",
      networkSpeed: "NetworkSpeed.qml",
      diskUsage: "DiskUsage.qml",
      temperature: "Temperature.qml"
    }
    return map[widgetId] || ""
  }

  // All enabled widgets — re-evaluates when config changes.
  readonly property var allEnabledIds: root.config ? Config.enabledWidgetIds(root.config) : []

  // Split into auto-positioned (no saved x/y) and manually positioned.
  // These are cached and only updated when the actual widget IDs change,
  // NOT on every config change. This prevents the Repeaters from
  // destroying and recreating all cards when an unrelated setting changes.
  property var cachedAutoIds: []
  property var cachedManualIds: []

  function autoIds() {
    var out = []
    var ids = root.allEnabledIds
    for (var i = 0; i < ids.length; i++) {
      var x = Config.widgetX(root.config, ids[i])
      var y = Config.widgetY(root.config, ids[i])
      if (x < 0 || y < 0) out.push(ids[i])
    }
    return out
  }

  function manualIds() {
    var out = []
    var ids = root.allEnabledIds
    for (var i = 0; i < ids.length; i++) {
      var x = Config.widgetX(root.config, ids[i])
      var y = Config.widgetY(root.config, ids[i])
      if (x >= 0 && y >= 0) out.push(ids[i])
    }
    return out
  }

  function arraysEqual(a, b) {
    if (a.length !== b.length) return false
    for (var i = 0; i < a.length; i++) {
      if (a[i] !== b[i]) return false
    }
    return true
  }

  // Update cached layout IDs only if they actually changed.
  // Returns true if the IDs changed (and Repeaters will update).
  function updateLayoutIds() {
    var newAuto = root.config ? autoIds() : []
    var newManual = root.config ? manualIds() : []
    var changed = false
    if (!arraysEqual(newAuto, root.cachedAutoIds)) {
      root.cachedAutoIds = newAuto
      changed = true
    }
    if (!arraysEqual(newManual, root.cachedManualIds)) {
      root.cachedManualIds = newManual
      changed = true
    }
    return changed
  }

  readonly property var autoLayoutIds: root.cachedAutoIds
  readonly property var manualLayoutIds: root.cachedManualIds

  readonly property color resolvedAccent: Theme.resolveAccent(root.config)
  readonly property color resolvedText: Theme.resolveTextColor(root.config)
  readonly property color resolvedCardBg: Theme.resolveCardColor(root.config)
  readonly property color resolvedBorder: Theme.resolveBorderColor(root.config)

  // Omarchy theme swaps mutate Color.foreground/background/accent. The
  // resolved* bindings above re-evaluate automatically, but the per-card
  // color props are pushed imperatively through applyWidgetProps(), which
  // only runs on widgetConfigRefresh. Re-emit that signal whenever the
  // foundational palette changes so cards recolor live without needing an
  // edit-mode toggle.
  Connections {
    target: Color
    function onForegroundChanged() { root.widgetConfigRefresh() }
    function onBackgroundChanged() { root.widgetConfigRefresh() }
    function onAccentChanged() { root.widgetConfigRefresh() }
    function onUrgentChanged() { root.widgetConfigRefresh() }
    function onMutedChanged() { root.widgetConfigRefresh() }
    function onShellValuesChanged() { root.widgetConfigRefresh() }
  }
  readonly property real cardRadius: {
    var v = root.config && root.config.global ? Number(root.config.global.cardRadius) : NaN
    return isFinite(v) ? v : 18
  }
  readonly property real gaugeDiameter: {
    var v = root.config && root.config.global ? Number(root.config.global.gaugeDiameter) : NaN
    return isFinite(v) && v > 0 ? v : 110
  }

  color: "transparent"
  exclusionMode: ExclusionMode.Ignore
  WlrLayershell.namespace: "io.github.tammyx44.omawidgets"
  WlrLayershell.layer: WlrLayer.Bottom
  WlrLayershell.keyboardFocus: WlrKeyboardFocus.None

  anchors { top: true; bottom: true; left: true; right: true }

  // Input mask: union of Regions, one per possible widget card.
  // Each Region uses `item:` to read a card's geometry directly.
  // Empty desktop areas are click-through. During drag, the dragged
  // card's Region follows it automatically because `item:` is live.
  // The cardLoadCounter dependency forces re-evaluation after cards load.
  // Context menu and settings panel are separate PanelWindow surfaces
  // on the Overlay layer — they handle their own input, not in this mask.
  mask: Region {
    Region { item: root.cardLoadCounter >= 0 ? root.interactiveCardItemFor("systemMonitor") : null }
    Region { item: root.cardLoadCounter >= 0 ? root.interactiveCardItemFor("battery") : null }
    Region { item: root.cardLoadCounter >= 0 ? root.interactiveCardItemFor("media") : null }
    Region { item: root.cardLoadCounter >= 0 ? root.interactiveCardItemFor("topProcesses") : null }
    Region { item: root.cardLoadCounter >= 0 ? root.interactiveCardItemFor("networkSpeed") : null }
    Region { item: root.cardLoadCounter >= 0 ? root.interactiveCardItemFor("diskUsage") : null }
    Region { item: root.cardLoadCounter >= 0 ? root.interactiveCardItemFor("temperature") : null }
  }

  // Liquid glass: blur only behind the cards, not the whole screen.
  // The blurRegionItem is an invisible Item that contains a Rectangle
  // for each card at its current position. The BackgroundEffect blurs
  // only the regions covered by these rectangles.
  // blurIntensity (0-100) controls how strong the blur is — exposed
  // in the settings panel as a slider.
  property real blurIntensity: root.config && root.config.global
    ? Number(root.config.global.blurIntensity) : 50
  property bool blurEnabled: root.config && root.config.global
    ? root.config.global.blurEnabled !== false : true

  BackgroundEffect.blurRegion: Region {
    item: blurRegionItem
  }

  Item {
    id: blurRegionItem
    visible: false
    Repeater {
      model: root.autoLayoutIds.concat(root.manualLayoutIds)
      Rectangle {
        required property string modelData
        property var cardLoader: {
          // Find the card Item for this widgetId
          for (var i = 0; i < autoRepeater.count; i++) {
            var l = autoRepeater.itemAt(i)
            if (l && l.item && l.item.widgetId === modelData) return l.item
          }
          for (var i = 0; i < manualRepeater.count; i++) {
            var l = manualRepeater.itemAt(i)
            if (l && l.item && l.item.widgetId === modelData) return l.item
          }
          return null
        }
        x: cardLoader ? cardLoader.x : 0
        y: cardLoader ? cardLoader.y : 0
        width: cardLoader ? cardLoader.width : 0
        height: cardLoader ? cardLoader.height : 0
        radius: root.cardRadius
        visible: cardLoader !== null && root.blurEnabled
      }
    }
  }

  FileView {
    id: configFile
    path: root.configPath
    watchChanges: true
    printErrors: false
    atomicWrites: true
    onLoaded: root.loadConfig(text())
    onFileChanged: reload()
    onLoadFailed: function(error) {
      if (error === FileViewError.FileNotFound && !root.configLoaded) root.loadConfig("")
      else {
        root.configError = "Could not read widget settings. Reload or explicitly reset to defaults."
        root.persistenceBlocked = true
      }
    }
    onSaved: {
      root.lastSavedText = root.inFlightText
      root.inFlightText = ""
      root.suppressFileWatch = false
      if (!root.persistenceBlocked && !root.externalConflict) root.configError = ""
      root.saveStatus = "Saved"
      if (root.pendingConfig) saveDebounceTimer.restart()
      saveWatchTimer.restart()
    }
    onSaveFailed: {
      root.inFlightText = ""
      root.suppressFileWatch = false
      root.pendingConfig = root.config
      root.configError = "Could not save settings. Your changes are still in memory."
      root.saveStatus = "Not saved"
    }
  }

  property bool configLoaded: false
  property bool persistenceBlocked: false
  property bool externalConflict: false
  property string configError: ""
  property string saveStatus: ""
  property string lastSavedText: ""
  property string inFlightText: ""
  property string externalText: ""

  function loadConfig(raw) {
    var text = String(raw || "")
    if (root.configLoaded && (text === root.lastSavedText || (root.inFlightText && text === root.inFlightText))) return
    if (root.configLoaded && (root.pendingConfig || root.inFlightText)) {
      root.externalText = text
      root.externalConflict = true
      root.configError = "Settings changed on disk. Reload them or keep your local changes."
      return
    }
    var parsed = Config.parseConfigResult(text)
    if (!parsed.ok) {
      root.configError = parsed.error
      root.persistenceBlocked = true
      return
    }
    root.config = parsed.config
    root.configLoaded = true
    root.lastSavedText = text
    root.persistenceBlocked = false
    root.configError = ""
    root.updateLayoutIds()
    root.widgetConfigRefresh()
  }

  function resolveConfigConflict(keepLocal) {
    var incoming = root.externalText
    root.externalConflict = false
    root.externalText = ""
    if (keepLocal) {
      root.persistenceBlocked = false
      root.saveConfig()
    } else {
      saveDebounceTimer.stop()
      root.pendingConfig = null
      root.lastSavedText = ""
      root.loadConfig(incoming)
    }
  }

  function retryConfigSave() {
    if (root.persistenceBlocked) configFile.reload()
    else root.saveConfig()
  }

  // Debounced save: updates the in-memory pending config immediately,
  // but only writes to disk after 500ms of no changes. This prevents
  // excessive disk I/O when dragging sliders in the settings panel.
  property var pendingConfig: null
  function saveConfig() {
    root.pendingConfig = root.config
    if (root.persistenceBlocked || root.externalConflict) return
    root.saveStatus = "Saving…"
    saveDebounceTimer.restart()
  }

  Timer {
    id: saveDebounceTimer
    interval: 500
    repeat: false
    onTriggered: {
      if (root.persistenceBlocked || root.externalConflict || root.inFlightText) return
      if (root.pendingConfig) {
        root.inFlightText = JSON.stringify(root.pendingConfig, null, 2) + "\n"
        root.pendingConfig = null
        root.suppressFileWatch = true
        configFile.setText(root.inFlightText)
      }
      // Re-enable watcher after the write settles
      saveWatchTimer.restart()
    }
  }

  Timer {
    id: saveWatchTimer
    interval: 150
    repeat: false
    onTriggered: if (!root.inFlightText) configFile.reload()
  }

  // --- Config mutation functions ---
  // Each creates a new object reference (shallow clone) so QML's
  // property var change signal fires and bindings re-evaluate.
  // Shallow clone is O(n) for one level — much faster than JSON deep-clone.
  function shallowClone(obj) {
    if (!obj || typeof obj !== "object") return obj
    var c = {}
    for (var k in obj) c[k] = obj[k]
    return c
  }

  function updateWidgetConfig(widgetId, key, value) {
    if (!root.config.widgets || !root.config.widgets[widgetId]) return
    var c = shallowClone(root.config)
    c.widgets = shallowClone(c.widgets)
    c.widgets[widgetId] = shallowClone(c.widgets[widgetId])
    c.widgets[widgetId][key] = value
    root.config = c
    root.updateLayoutIds()
    root.widgetConfigRefresh()
    root.saveConfig()
  }

  function updateWidgetPosition(widgetId, x, y) {
    if (!root.config.widgets || !root.config.widgets[widgetId]) return
    var c = shallowClone(root.config)
    c.widgets = shallowClone(c.widgets)
    c.widgets[widgetId] = shallowClone(c.widgets[widgetId])
    c.widgets[widgetId].x = Math.round(x)
    c.widgets[widgetId].y = Math.round(y)
    root.config = c
    root.updateLayoutIds()
    root.widgetConfigRefresh()
    root.saveConfig()
  }

  // Handles flat global keys (cardRadius, gaugeDiameter, cardSpacing,
  // blurEnabled, blurIntensity) by writing into config.global, and
  // top-level keys (layout, themeMode) by writing directly on config.
  function updateGlobalConfig(key, value) {
    var c = shallowClone(root.config)
    if (key === "cardRadius" || key === "gaugeDiameter" || key === "cardSpacing"
        || key === "blurEnabled" || key === "blurIntensity"
        || key === "gaugeColorMode") {
      c.global = shallowClone(c.global || {})
      c.global[key] = value
    } else if (key === "global" && typeof value === "object") {
      c.global = shallowClone(value)
    } else {
      c[key] = value
    }
    root.config = c
    root.updateLayoutIds()
    root.widgetConfigRefresh()
    root.saveConfig()
  }

  function updateColorConfig(key, value) {
    var c = shallowClone(root.config)
    c.colors = shallowClone(c.colors || {})
    c.colors[key] = value
    root.config = c
    root.updateLayoutIds()
    root.widgetConfigRefresh()
    root.saveConfig()
  }

  function resetConfig() {
    root.persistenceBlocked = false
    root.externalConflict = false
    root.configError = ""
    root.config = Config.defaultConfig()
    root.updateLayoutIds()
    root.widgetConfigRefresh()
    root.saveConfig()
  }

  function showContextMenu(widgetId, x, y) {
    root.contextMenuWidgetId = widgetId
    var safeX = Number(x)
    var safeY = Number(y)
    root.contextMenuX = isFinite(safeX) ? safeX : root.width / 2
    root.contextMenuY = isFinite(safeY) ? safeY : root.height / 2
    root.contextMenuVisible = true
  }

  function hideContextMenu() {
    root.contextMenuVisible = false
  }

  function showSettings() {
    root.settingsVisible = true
  }

  function hideSettings() {
    root.settingsVisible = false
  }

  function toggleEditMode() {
    root.editMode = !root.editMode
    root.widgetConfigRefresh()
  }

  function resetAllPositions() {
    if (!root.config.widgets) return
    var c = shallowClone(root.config)
    c.widgets = shallowClone(c.widgets)
    var ids = Config.allWidgetIds()
    for (var i = 0; i < ids.length; i++) {
      if (c.widgets[ids[i]]) {
        c.widgets[ids[i]] = shallowClone(c.widgets[ids[i]])
        c.widgets[ids[i]].x = -1
        c.widgets[ids[i]].y = -1
      }
    }
    root.config = c
    root.updateLayoutIds()
    root.widgetConfigRefresh()
    root.saveConfig()
  }

  // Get the actual height of a loaded card by widget ID.
  // Searches both the auto and manual repeaters.
  function cardHeightFor(widgetId) {
    // Search auto repeater
    var autoIds = root.autoLayoutIds
    for (var i = 0; i < autoIds.length; i++) {
      if (autoIds[i] === widgetId) {
        var loader = autoRepeater.itemAt(i)
        if (loader && loader.item && loader.item.height > 0)
          return loader.item.height
      }
    }
    // Search manual repeater
    var manualIds = root.manualLayoutIds
    for (var j = 0; j < manualIds.length; j++) {
      if (manualIds[j] === widgetId) {
        var mloader = manualRepeater.itemAt(j)
        if (mloader && mloader.item && mloader.item.height > 0)
          return mloader.item.height
      }
    }
    return cachedCardHeight(widgetId) // fallback to cached size
  }

  // Get the actual width of a loaded card by widget ID.
  function cardWidthFor(widgetId) {
    var autoIds = root.autoLayoutIds
    for (var i = 0; i < autoIds.length; i++) {
      if (autoIds[i] === widgetId) {
        var loader = autoRepeater.itemAt(i)
        if (loader && loader.item && loader.item.width > 0)
          return loader.item.width
      }
    }
    var manualIds = root.manualLayoutIds
    for (var j = 0; j < manualIds.length; j++) {
      if (manualIds[j] === widgetId) {
        var mloader = manualRepeater.itemAt(j)
        if (mloader && mloader.item && mloader.item.width > 0)
          return mloader.item.width
      }
    }
    return cachedCardWidth(widgetId) // fallback to cached size
  }

  // Collect all card rectangles (x, y, width, height) except the one being dragged.
  // Searches both auto and manual repeaters.
  function getAllCardRects(excludeWidgetId) {
    var rects = []
    var autoIds = root.autoLayoutIds
    for (var i = 0; i < autoIds.length; i++) {
      if (autoIds[i] === excludeWidgetId) continue
      var loader = autoRepeater.itemAt(i)
      if (loader && loader.item) {
        rects.push({
          widgetId: autoIds[i],
          x: loader.item.x, y: loader.item.y,
          width: loader.item.width, height: loader.item.height
        })
      }
    }
    var manualIds = root.manualLayoutIds
    for (var j = 0; j < manualIds.length; j++) {
      if (manualIds[j] === excludeWidgetId) continue
      var mloader = manualRepeater.itemAt(j)
      if (mloader && mloader.item) {
        rects.push({
          widgetId: manualIds[j],
          x: mloader.item.x, y: mloader.item.y,
          width: mloader.item.width, height: mloader.item.height
        })
      }
    }
    return rects
  }

  // Check if two rectangles overlap (with a small padding gap).
  // Returns true if they overlap.
  function rectsOverlap(r1, r2, padding) {
    var p = padding || 0
    return !(r1.x + r1.width + p <= r2.x ||
             r2.x + r2.width + p <= r1.x ||
             r1.y + r1.height + p <= r2.y ||
             r2.y + r2.height + p <= r1.y)
  }

  // Given a desired position for the dragged card, resolve collisions
  // by pushing the card to the nearest non-overlapping position.
  // Tries: original position, then shifted in each direction, then clamped.
  // Optimized to avoid creating temporary objects in the inner loop.
  function resolveDragCollision(widgetId, desiredX, desiredY, cardW, cardH) {
    var others = getAllCardRects(widgetId)
    if (others.length === 0) return { x: desiredX, y: desiredY }

    var gap = 4 // minimum gap between cards

    // Check if the desired position is already collision-free
    // (inline rectsOverlap to avoid function call overhead)
    var collision = false
    for (var i = 0; i < others.length; i++) {
      var o = others[i]
      if (!(desiredX + cardW + gap <= o.x ||
            o.x + o.width + gap <= desiredX ||
            desiredY + cardH + gap <= o.y ||
            o.y + o.height + gap <= desiredY)) {
        collision = true
        break
      }
    }
    if (!collision) return { x: desiredX, y: desiredY }

    // Try shifting in 4 directions to find the nearest non-overlapping spot
    var bestX = desiredX
    var bestY = desiredY
    var bestDist = Infinity
    var step = 8
    var maxSteps = 80 // search up to 640px away
    var maxW = root.width - cardW
    var maxH = root.height - cardH

    for (var dir = 0; dir < 4; dir++) {
      for (var s = 1; s <= maxSteps; s++) {
        var testX = desiredX
        var testY = desiredY
        if (dir === 0) testY = desiredY - s * step // up
        else if (dir === 1) testY = desiredY + s * step // down
        else if (dir === 2) testX = desiredX - s * step // left
        else testX = desiredX + s * step // right

        // Clamp to screen
        if (testX < 0) testX = 0
        else if (testX > maxW) testX = maxW
        if (testY < root.barOffset) testY = root.barOffset
        else if (testY > maxH) testY = maxH

        // Inline overlap check — no temp object allocation
        var hasCollision = false
        for (var j = 0; j < others.length; j++) {
          var o2 = others[j]
          if (!(testX + cardW + gap <= o2.x ||
                o2.x + o2.width + gap <= testX ||
                testY + cardH + gap <= o2.y ||
                o2.y + o2.height + gap <= testY)) {
            hasCollision = true
            break
          }
        }
        if (!hasCollision) {
          var dist = Math.abs(testX - desiredX) + Math.abs(testY - desiredY)
          if (dist < bestDist) {
            bestDist = dist
            bestX = testX
            bestY = testY
          }
          break // found nearest in this direction
        }
      }
    }

    return { x: bestX, y: bestY }
  }

  // Apply a position preset to all enabled widgets.
  // Uses actual card heights for accurate stacking.
  function applyPreset(preset) {
    if (!root.config.widgets) return
    var ids = root.allEnabledIds
    if (ids.length === 0) return
    var c = shallowClone(root.config)
    c.widgets = shallowClone(c.widgets)

    var screenW = root.width
    var screenH = root.height
    var bar = root.barOffset + root.edgeMargin
    var margin = root.edgeMargin
    var gap = root.cardSpacing
    var bottomLimit = screenH - root.dockOffset - margin
    var usableW = screenW - 2 * margin

    // For Top/Bottom presets, use a tighter gap to fit more cards per row
    if (preset === "top" || preset === "bottom") {
      gap = Math.min(gap, 8)
      margin = Math.min(margin, 16)
      usableW = screenW - 2 * margin
    }

    // Helper: set widget position in config
    function setPos(wid, x, y) {
      if (!c.widgets[wid]) return
      c.widgets[wid] = shallowClone(c.widgets[wid])
      c.widgets[wid].x = Math.round(x)
      c.widgets[wid].y = Math.round(y)
    }

    if (preset === "spread") {
      // Spread = auto layout (reset to -1, -1)
      for (var i = 0; i < ids.length; i++) {
        setPos(ids[i], -1, -1)
      }
    } else if (preset === "left") {
      // 2-column stack on the left edge. Balance cards by height into 2 columns.
      // Col 1 starts at margin, Col 2 starts at margin + col1Width + gap.
      var lNumCols = ids.length > 3 ? 2 : 1
      // Greedy bin-packing: assign each card to the shorter column
      var lCols = [[], []]
      var lColH = [0, 0]
      var lColW = [0, 0]
      for (var li = 0; li < ids.length; li++) {
        var lh = cardHeightFor(ids[li])
        var lw = cardWidthFor(ids[li])
        // Pick the shorter column
        var target = lNumCols === 1 || lColH[0] <= lColH[1] ? 0 : 1
        lCols[target].push(ids[li])
        lColH[target] += lh + gap
        lColW[target] = Math.max(lColW[target], lw)
      }
      // Place columns
      var lX = margin
      for (var lc = 0; lc < lNumCols; lc++) {
        if (lCols[lc].length === 0) continue
        var lY = bar
        for (var li2 = 0; li2 < lCols[lc].length; li2++) {
          var lh2 = cardHeightFor(lCols[lc][li2])
          setPos(lCols[lc][li2], lX, lY)
          lY += lh2 + gap
        }
        lX += lColW[lc] + gap
      }
    } else if (preset === "right") {
      // 2-column stack on the right edge. Balance cards by height into 2 columns.
      // Columns are right-aligned to the screen edge.
      var rNumCols = ids.length > 3 ? 2 : 1
      var rCols = [[], []]
      var rColH = [0, 0]
      var rColW = [0, 0]
      for (var ri = 0; ri < ids.length; ri++) {
        var rh = cardHeightFor(ids[ri])
        var rw = cardWidthFor(ids[ri])
        var target = rNumCols === 1 || rColH[0] <= rColH[1] ? 0 : 1
        rCols[target].push(ids[ri])
        rColH[target] += rh + gap
        rColW[target] = Math.max(rColW[target], rw)
      }
      // Place columns from right to left
      var rX = screenW - margin
      for (var rc = rNumCols - 1; rc >= 0; rc--) {
        if (rCols[rc].length === 0) continue
        var rY = bar
        // Right-align this column to rX
        var colLeftEdge = rX - rColW[rc]
        for (var ri2 = 0; ri2 < rCols[rc].length; ri2++) {
          var rh2 = cardHeightFor(rCols[rc][ri2])
          var rw2 = cardWidthFor(rCols[rc][ri2])
          // Right-align card within column
          setPos(rCols[rc][ri2], rX - rw2, rY)
          rY += rh2 + gap
        }
        rX -= rColW[rc] + gap
      }
    } else if (preset === "top") {
      // Arrange cards in rows starting from the top, wrapping when too wide.
      // Each row: cards share top Y, row advances by max card height.
      var tx = margin
      var ty = bar
      var tRowMaxH = 0
      for (var ti = 0; ti < ids.length; ti++) {
        var tw = cardWidthFor(ids[ti])
        var th = cardHeightFor(ids[ti])
        if (tx + tw > screenW - margin && tx > margin) {
          tx = margin
          ty += tRowMaxH + gap
          tRowMaxH = 0
        }
        setPos(ids[ti], tx, ty)
        tx += tw + gap
        tRowMaxH = Math.max(tRowMaxH, th)
      }
    } else if (preset === "bottom") {
      // Arrange cards in rows anchored to the bottom edge (above dock).
      // Build rows forward, then place from bottom up.
      var bRows = []
      var bRow = []
      var bRowW = 0
      for (var bi = 0; bi < ids.length; bi++) {
        var bw = cardWidthFor(ids[bi])
        if (bRowW + bw > usableW && bRow.length > 0) {
          bRows.push(bRow)
          bRow = []
          bRowW = 0
        }
        bRow.push(ids[bi])
        bRowW += bw + gap
      }
      if (bRow.length > 0) bRows.push(bRow)

      // Calculate each row's max height first
      var bRowMaxHeights = []
      for (var bri2 = 0; bri2 < bRows.length; bri2++) {
        var rmh = 0
        for (var rj2 = 0; rj2 < bRows[bri2].length; rj2++) {
          rmh = Math.max(rmh, cardHeightFor(bRows[bri2][rj2]))
        }
        bRowMaxHeights.push(rmh)
      }

      // Place rows from bottom up, anchored above the dock
      var bBottomY = bottomLimit
      for (var bri = bRows.length - 1; bri >= 0; bri--) {
        var row = bRows[bri]
        var rowMaxH = bRowMaxHeights[bri]
        // Top of this row = bBottomY - rowMaxH
        var rowTopY = bBottomY - rowMaxH
        // Place cards in this row, top-aligned to row's top edge
        var bX = margin
        for (var rk = 0; rk < row.length; rk++) {
          var rh2 = cardHeightFor(row[rk])
          var rw2 = cardWidthFor(row[rk])
          // Top-align: card top = rowTopY
          setPos(row[rk], bX, rowTopY)
          bX += rw2 + gap
        }
        bBottomY = rowTopY - gap
      }
    } else if (preset === "center") {
      // Balanced 2-column grid, centered on screen both axes.
      // Use greedy bin-packing to balance column heights.
      var cNumCols = ids.length > 4 ? 2 : 1
      var cCols = [[], []]
      var cColH = [0, 0]
      var cColW = [0, 0]
      for (var ci2 = 0; ci2 < ids.length; ci2++) {
        var ch2 = cardHeightFor(ids[ci2])
        var cwd = cardWidthFor(ids[ci2])
        var cTarget = cNumCols === 1 || cColH[0] <= cColH[1] ? 0 : 1
        cCols[cTarget].push(ids[ci2])
        cColH[cTarget] += ch2 + gap
        cColW[cTarget] = Math.max(cColW[cTarget], cwd)
      }

      // Total block dimensions
      var cTotalW = 0
      var cMaxH = 0
      for (var ccw = 0; ccw < cNumCols; ccw++) {
        if (cCols[ccw].length === 0) continue
        cTotalW += cColW[ccw] + (ccw > 0 ? gap : 0)
        cMaxH = Math.max(cMaxH, cColH[ccw] - gap)
      }

      // Center the block, accounting for bar at top and dock at bottom
      var cAvailH = bottomLimit - bar
      var cStartX = (screenW - cTotalW) / 2
      var cStartY = bar + Math.max(0, (cAvailH - cMaxH) / 2)

      // Place cards
      var cX = cStartX
      for (var col2 = 0; col2 < cNumCols; col2++) {
        if (cCols[col2].length === 0) continue
        var cY = cStartY
        for (var item2 = 0; item2 < cCols[col2].length; item2++) {
          var ih2 = cardHeightFor(cCols[col2][item2])
          var iw2 = cardWidthFor(cCols[col2][item2])
          // Center card within its column
          setPos(cCols[col2][item2], cX + (cColW[col2] - iw2) / 2, cY)
          cY += ih2 + gap
        }
        cX += cColW[col2] + gap
      }
    }

    root.config = c
    root.updateLayoutIds()
    root.widgetConfigRefresh()
    root.saveConfig()
    relayoutTimer.restart()
  }

  // IPC handler — allows opening settings and toggling edit mode
  // from keybindings or the bar widget.
  IpcHandler {
    target: "io.github.tammyx44.omawidgets"

    function openSettings(): void {
      root.settingsVisible = true
    }
    function openWidgetSettings(widgetId: string): void {
      root.settingsVisible = true
      Qt.callLater(function() {
        settingsPanel.showWidgetSettings(widgetId)
      })
    }
    function closeSettings(): void {
      root.settingsVisible = false
    }
    function toggleEdit(): void {
      root.editMode = !root.editMode
    }
    function preset(presetName: string): void {
      root.applyPreset(presetName)
    }
    function rescan(): void {
      configFile.reload()
    }
  }

  Component.onCompleted: configFile.reload()

  // Push config + visual props into a loaded widget item.
  // Called on initial load and again on every configChanged.
  function applyWidgetProps(item, widgetId) {
    if (!item) return
    item.widgetId = widgetId
    item.config = root.config
    item.cardColor = root.resolvedCardBg
    item.borderColor = root.resolvedBorder
    item.textColor = root.resolvedText
    item.accentColor = root.resolvedAccent
    item.cardRadius = root.cardRadius
    item.gaugeDiameter = root.gaugeDiameter
  }

  // Cache of last known card sizes by widget ID.
  // Used to give newly created cards a stable initial size instead of
  // the 300x200 fallback, preventing the "disorientation" shift when
  // toggling widgets on/off.
  property var cardSizeCache: ({})

  function cacheCardSize(widgetId, w, h) {
    if (w > 0 && h > 0) {
      var cache = {}
      for (var k in root.cardSizeCache) cache[k] = root.cardSizeCache[k]
      cache[widgetId] = { width: w, height: h }
      root.cardSizeCache = cache
    }
  }

  function cachedCardWidth(widgetId) {
    var c = root.cardSizeCache[widgetId]
    return c ? c.width : root.cardWidth
  }

  function cachedCardHeight(widgetId) {
    var c = root.cardSizeCache[widgetId]
    return c ? c.height : 200
  }

  // --- Card component ---
  // Used by both Flow (auto) and Repeater (manual).
  // Dragging always works. Right-click uses TapHandler (no child interference).
  Component {
    id: widgetCard

    Item {
      id: card
      property string widgetId: ""
      property bool isManual: false

      // Size tracks the loaded widget item. Before the item is ready,
      // we use a static initial size (set once in onCompleted) to prevent
      // the 300x200 fallback jump. Using a plain property (not a binding
      // on root.cardSizeCache) avoids a binding loop.
      property real initialW: root.cardWidth
      property real initialH: 200
      width: cardLoader.item ? cardLoader.item.width : card.initialW
      height: cardLoader.item ? cardLoader.item.height : card.initialH

      // Trigger relayout only during initial load (first 2 seconds).
      // After that, data-driven size changes (e.g. media starting/stopping)
      // should NOT trigger a relayout of all cards — that causes jitter.
      property bool hasSettled: false

      // Smooth position animation for auto-positioned cards.
      // When relayout moves cards, they slide instead of jumping.
      // Disabled during drag (manual positioning) and for manual cards.
      Behavior on x {
        enabled: !card.isManual && !root.dragInProgress
        NumberAnimation { duration: 200; easing.type: Easing.OutCubic }
      }
      Behavior on y {
        enabled: !card.isManual && !root.dragInProgress
        NumberAnimation { duration: 200; easing.type: Easing.OutCubic }
      }

      // Fade in new cards so they don't appear abruptly.
      // The target opacity is the per-card config opacity (default 1.0).
      property real targetOpacity: Config.widgetCardOpacity(root.config, card.widgetId)
      opacity: 0
      Behavior on opacity {
        NumberAnimation { duration: 200; easing.type: Easing.OutCubic }
      }

      // Combined init: set cached size, fade in, start settle timer
      Component.onCompleted: {
        var c = root.cardSizeCache[card.widgetId]
        if (c) {
          card.initialW = c.width
          card.initialH = c.height
        }
        fadeInTimer.restart()
        settleTimer.restart()
      }
      Timer {
        id: fadeInTimer
        interval: 50
        repeat: false
        onTriggered: card.opacity = card.targetOpacity
      }
      Timer {
        id: settleTimer
        interval: 2000
        repeat: false
        onTriggered: card.hasSettled = true
      }

      // Cache size + trigger relayout during initial load
      onWidthChanged: {
        if (!isManual) root.cacheCardSize(card.widgetId, width, height)
        if (!root.dragInProgress) relayoutTimer.restart()
      }
      onHeightChanged: {
        if (!isManual) root.cacheCardSize(card.widgetId, width, height)
        if (!root.dragInProgress) relayoutTimer.restart()
      }

      // Hide the entire card when the widget itself is invisible.
      visible: cardLoader.item ? cardLoader.item.visible : true

      // Click-through: when enabled, the card ignores all mouse input.
      readonly property bool clickThrough: !root.editMode && Config.widgetClickThrough(root.config, card.widgetId)

      // Soft drop shadow behind the card for elevation
      Rectangle {
        anchors.fill: parent
        anchors.margins: -4
        radius: root.cardRadius + 4
        color: Qt.rgba(0, 0, 0, 0.35)
        z: -1
        opacity: 0.8
      }

      // Edit mode highlight border (visual only)
      Rectangle {
        anchors.fill: parent
        anchors.margins: -3
        radius: root.cardRadius + 3
        color: "transparent"
        border.color: root.resolvedAccent
        border.width: 2
        z: 2
        visible: root.editMode
        opacity: dragHandler.active ? 0.9 : 0.5
        Behavior on opacity { NumberAnimation { duration: 200 } }
      }

      Loader {
        id: cardLoader
        source: root.widgetSourceUrl(card.widgetId)
        onLoaded: root.applyWidgetProps(item, card.widgetId)
      }

      // Re-apply props when config changes
      Connections {
        target: root
        function onWidgetConfigRefresh() {
          root.applyWidgetProps(cardLoader.item, card.widgetId)
          // Apply per-card opacity reactively
          if (card.opacity > 0) card.opacity = card.targetOpacity
        }
      }

      // Right-click context menu via TapHandler
      TapHandler {
        acceptedButtons: Qt.RightButton
        enabled: !card.clickThrough
        onTapped: function(eventPoint) {
          // Cards are direct children of root, so card.x/card.y are
          // already in screen coordinates.
          root.showContextMenu(card.widgetId, card.x + eventPoint.position.x, card.y + eventPoint.position.y)
        }
      }

      // Drag handler — always enabled.
      // Drag handler — always enabled, but doesn't own the card's position.
      // Uses target: null and manually updates card.x/card.y so that
      // the relayout function can freely set positions without conflict.
      property real dragStartX: 0
      property real dragStartY: 0

      DragHandler {
        id: dragHandler
        target: null
        xAxis.enabled: true
        yAxis.enabled: true
        margin: 4
        // Only allow dragging when edit mode is ON.
        // cursorShape must be conditional — Qt's default SizeAllCursor
        // can leak even when the handler is disabled on some versions.
        cursorShape: root.editMode ? Qt.SizeAllCursor : Qt.ArrowCursor
        enabled: root.editMode && !card.clickThrough

        onActiveChanged: {
          if (active) {
            root.dragInProgress = true
            card.z = 100  // bring dragged card to front
            card.dragStartX = card.x
            card.dragStartY = card.y
            if (!card.isManual) {
              // Convert from auto to manual
              card.isManual = true
              // Reparent to root's content item for free positioning
              var p = root.contentItem
              var localPos = card.mapToItem(p, 0, 0)
              card.parent = p
              card.dragStartX = localPos.x
              card.dragStartY = localPos.y
              card.x = localPos.x
              card.y = localPos.y
            }
          }
          if (!active && card.isManual) {
            // Save position when drag ends, clamped to screen
            var finalX = Math.max(0, Math.min(card.x, root.width - card.width))
            var finalY = Math.max(root.barOffset, Math.min(card.y, root.height - card.height))
            // Final collision resolution
            var finalResolved = root.resolveDragCollision(card.widgetId, finalX, finalY, card.width, card.height)
            card.x = finalResolved.x
            card.y = finalResolved.y
            var completedId = card.widgetId
            Qt.callLater(function() { root.updateWidgetPosition(completedId, finalResolved.x, finalResolved.y) })
            // Restore z-order and unfreeze relayout
            card.z = 0
            root.dragInProgress = false
            relayoutTimer.restart()
          }
        }

        onTranslationChanged: {
          if (active) {
            var newX = card.dragStartX + translation.x
            var newY = card.dragStartY + translation.y
            // Clamp to screen
            newX = Math.max(0, Math.min(newX, root.width - card.width))
            newY = Math.max(root.barOffset, Math.min(newY, root.height - card.height))
            // Resolve collisions with other cards
            var resolved = root.resolveDragCollision(card.widgetId, newX, newY, card.width, card.height)
            card.x = resolved.x
            card.y = resolved.y
          }
        }
      }
    }
  }

  // --- Auto-positioned cards ---
  // Cards are direct children of root, positioned manually.
  // A Timer delays layout until all cards have loaded their content,
  // so we know their actual heights.
  Repeater {
    id: autoRepeater
    model: root.autoLayoutIds

    Loader {
      id: autoLoader
      required property var modelData
      sourceComponent: widgetCard
      onLoaded: {
        if (item) {
          item.widgetId = modelData
          item.isManual = false
          // Trigger a relayout after each card loads
          relayoutTimer.restart()
          // Force mask re-evaluation so input region picks up this card
          root.cardLoadCounter++
        }
      }

      Connections {
        target: root
        function onWidgetConfigRefresh() {
          relayoutTimer.restart()
        }
      }
    }
  }

  // Relayout timer — waits a brief moment for all card sizes to settle,
  // then positions them. A longer interval gives widgets time to load
  // their content and report their actual heights.
  Timer {
    id: relayoutTimer
    interval: 300
    repeat: false
    onTriggered: root.relayoutAutoCards()
  }

  property string layoutWarning: ""
  onWidthChanged: relayoutTimer.restart()
  onHeightChanged: relayoutTimer.restart()

  function relayoutAutoCards() {
    if (root.dragInProgress) return
    root.layoutWarning = ""
    var ids = root.autoLayoutIds
    var maxWidth = root.width - 2 * root.edgeMargin
    var x = root.edgeMargin
    var y = root.barOffset + root.edgeMargin
    var rowHeight = 0
    for (var i = 0; i < ids.length; i++) {
      var loader = autoRepeater.itemAt(i)
      if (!loader || !loader.item) continue
      var card = loader.item
      if (card.isManual) continue
      if (x + card.width > maxWidth + root.edgeMargin && x > root.edgeMargin) {
        x = root.edgeMargin
        y += rowHeight + root.cardSpacing
        rowHeight = 0
      }
      card.x = x
      card.y = y
      x += card.width + root.cardSpacing
      rowHeight = Math.max(rowHeight, card.height)
    }
    var rects = []
    for (var j = 0; j < root.allEnabledIds.length; j++) {
      var item = root.cardItemFor(root.allEnabledIds[j])
      if (!item) continue
      item.x = Math.max(0, Math.min(item.x, root.width - item.width))
      item.y = Math.max(root.barOffset, Math.min(item.y, root.height - root.dockOffset - item.height))
      var rect = { x: item.x, y: item.y, width: item.width, height: item.height }
      if (rect.width > root.width || rect.y + rect.height > root.height - root.dockOffset)
        root.layoutWarning = "Cards do not fit. Reduce card sizes or disable a widget."
      for (var k = 0; k < rects.length; k++) {
        if (root.rectsOverlap(rect, rects[k], 0)) root.layoutWarning = "Cards overlap. Try a layout preset or reduce card sizes."
      }
      rects.push(rect)
    }
  }

  // --- Manual-positioned cards (dragged out of Flow) ---
  Repeater {
    id: manualRepeater
    model: root.manualLayoutIds

    Loader {
      id: manualLoader
      required property var modelData
      sourceComponent: widgetCard
      onLoaded: {
        if (item) {
          item.widgetId = modelData
          item.isManual = true
          // No reparenting needed — the Repeater already places items
          // in the same coordinate space as the Flow.
          var x = Config.widgetX(root.config, modelData)
          var y = Config.widgetY(root.config, modelData)
          item.x = x >= 0 ? x : 0
          item.y = y >= 0 ? y : 0
          // Force mask re-evaluation so input region picks up this card
          root.cardLoadCounter++
        }
      }

      Connections {
        target: root
        function onWidgetConfigRefresh() {
          if (manualLoader.item) {
            var x = Config.widgetX(root.config, manualLoader.modelData)
            var y = Config.widgetY(root.config, manualLoader.modelData)
            if (x >= 0 && y >= 0) {
              manualLoader.item.x = x
              manualLoader.item.y = y
            }
          }
        }
      }
    }
  }

  // --- Context menu ---
  WidgetContextMenu {
    id: contextMenu
    widgetId: root.contextMenuWidgetId
    config: root.config
    editMode: root.editMode
    cardColor: Color.popups.background
    borderColor: Color.popups.border
    textColor: Color.popups.text
    accentColor: root.resolvedAccent
    visible: root.contextMenuVisible

    onWidgetConfigChanged: root.updateWidgetConfig(widgetId, key, value)
    onOpenSettings: root.showSettings()
    onEditModeToggleRequested: root.toggleEditMode()
    onVisibleChanged: if (!visible) root.hideContextMenu()

    // Position the menu when it becomes visible
    Connections {
      target: root
      function onContextMenuVisibleChanged() {
        if (root.contextMenuVisible) {
          contextMenu.show(root.contextMenuX, root.contextMenuY)
        }
      }
    }
  }

  // --- Settings panel ---
  // PanelWindow components can't be reliably loaded inside a Loader
  // (they may not create a separate Wayland surface). Instead, always
  // load it and control visibility via the `visible` property.
  SettingsPanel {
    id: settingsPanel
    configError: root.configError
    layoutWarning: root.layoutWarning
    saveStatus: root.saveStatus
    externalConflict: root.externalConflict
    onRetrySaveRequested: root.retryConfigSave()
    onResolveConflictRequested: function(keepLocal) { root.resolveConfigConflict(keepLocal) }
    config: root.config
    editMode: root.editMode
    visible: root.settingsVisible

    onWidgetConfigChanged: root.updateWidgetConfig(widgetId, key, value)
    onGlobalConfigChanged: root.updateGlobalConfig(key, value)
    onColorConfigChanged: root.updateColorConfig(key, value)
    onResetRequested: root.resetConfig()
    onResetPositionsRequested: root.resetAllPositions()
    onEditModeToggleRequested: root.toggleEditMode()
    onPresetRequested: root.applyPreset(preset)
    onCloseRequested: root.hideSettings()
  }

  // Live-update the context menu's editMode when it changes
  Connections {
    target: root
    function onWidgetConfigRefresh() {
      contextMenu.config = root.config
      contextMenu.editMode = root.editMode
    }
  }

  // Live-update the settings panel when config changes from any source.
  Connections {
    target: root
    function onWidgetConfigRefresh() {
      settingsPanel.config = root.config
      settingsPanel.editMode = root.editMode
    }
  }
}
